package com.myspace.uha40;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class contrevenant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String nom;
	private java.lang.String prenom;
	private java.lang.Integer age;
	private boolean permis_valide;
	private java.lang.Integer permis_point;

	private java.lang.Boolean vitesse_controlled;

	private java.lang.Boolean alcool_controlled;

	public contrevenant() {
	}

	public java.lang.String getNom() {
		return this.nom;
	}

	public void setNom(java.lang.String nom) {
		this.nom = nom;
	}

	public java.lang.String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(java.lang.String prenom) {
		this.prenom = prenom;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public boolean isPermis_valide() {
		return this.permis_valide;
	}

	public void setPermis_valide(boolean permis_valide) {
		this.permis_valide = permis_valide;
	}

	public java.lang.Integer getPermis_point() {
		return this.permis_point;
	}

	public void setPermis_point(java.lang.Integer permis_point) {
		this.permis_point = permis_point;
	}

	public java.lang.Boolean getVitesse_controlled() {
		return this.vitesse_controlled;
	}

	public void setVitesse_controlled(java.lang.Boolean vitesse_controlled) {
		this.vitesse_controlled = vitesse_controlled;
	}

	public java.lang.Boolean getAlcool_controlled() {
		return this.alcool_controlled;
	}

	public void setAlcool_controlled(java.lang.Boolean alcool_controlled) {
		this.alcool_controlled = alcool_controlled;
	}

	public contrevenant(java.lang.String nom, java.lang.String prenom,
			java.lang.Integer age, boolean permis_valide,
			java.lang.Integer permis_point,
			java.lang.Boolean vitesse_controlled,
			java.lang.Boolean alcool_controlled) {
		this.nom = nom;
		this.prenom = prenom;
		this.age = age;
		this.permis_valide = permis_valide;
		this.permis_point = permis_point;
		this.vitesse_controlled = vitesse_controlled;
		this.alcool_controlled = alcool_controlled;
	}

}