package com.myspace.uha40;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class controle implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String route_type;
	private java.lang.Integer vitesse;
	private java.lang.Double taux_alcool;

	public controle() {
	}

	public java.lang.String getRoute_type() {
		return this.route_type;
	}

	public void setRoute_type(java.lang.String route_type) {
		this.route_type = route_type;
	}

	public java.lang.Integer getVitesse() {
		return this.vitesse;
	}

	public void setVitesse(java.lang.Integer vitesse) {
		this.vitesse = vitesse;
	}

	public java.lang.Double getTaux_alcool() {
		return this.taux_alcool;
	}

	public void setTaux_alcool(java.lang.Double taux_alcool) {
		this.taux_alcool = taux_alcool;
	}

	public controle(java.lang.String route_type, java.lang.Integer vitesse,
			java.lang.Double taux_alcool) {
		this.route_type = route_type;
		this.vitesse = vitesse;
		this.taux_alcool = taux_alcool;
	}

}